import type { Metadata } from "next";
import AuthWrapper from "@/components/auth/AuthWrapper";
import GlobalProviders from "@/components/providers/Providers";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthWrapper authUrl={process.env.NEXT_PUBLIC_AUTH_URL!} redirectUrl="/">
      <GlobalProviders>{children}</GlobalProviders>
    </AuthWrapper>
  );
}
