import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import AuthWrapper from "@/components/auth/AuthWrapper";
import GlobalProviders from "@/components/providers/Providers";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AuthWrapper
          authUrl={process.env.NEXT_PUBLIC_AUTH_URL!}
          redirectUrl="/"
        >
          <GlobalProviders>{children}</GlobalProviders>
        </AuthWrapper>
      </body>
    </html>
  );
}
